In [2]:
#loading the data
import numpy as np
import pandas as pd

In [3]:
df1 =pd.read_csv(r'ipl_2008_2024_complete.csv')

In [4]:
df1

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
0,335982,1,205,17,3,124,15,14,45,Kolkata Knight Riders,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
1,335982,2,63,19,10,101,3,3,65,Royal Challengers Bangalore,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
2,335983,1,234,6,5,124,20,16,39,Chennai Super Kings,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
3,335983,2,196,11,4,124,18,9,33,Kings XI Punjab,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
4,335984,1,122,7,8,122,14,3,60,Rajasthan Royals,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2212,1426310,2,168,6,6,119,20,5,40,Rajasthan Royals,...,2024-05-22,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,R Ashwin,NaN,2024.0,1.0
2213,1426311,1,167,8,9,127,11,9,48,Sunrisers Hyderabad,...,2024-05-24,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Rajasthan Royals,field,Sunrisers Hyderabad,Shahbaz Ahmed,NaN,2024.0,0.0
2214,1426311,2,134,5,7,124,13,5,59,Rajasthan Royals,...,2024-05-24,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Rajasthan Royals,field,Sunrisers Hyderabad,Shahbaz Ahmed,NaN,2024.0,0.0
2215,1426312,1,100,13,10,117,8,3,62,Sunrisers Hyderabad,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,bat,Kolkata Knight Riders,MA Starc,NaN,2024.0,0.0
2216,1426312,2,103,11,2,67,10,6,28,Kolkata Knight Riders,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,bat,Kolkata Knight Riders,MA Starc,NaN,2024.0,0.0

In [5]:
#Load the CSV into a Pandas DataFrame and display: shape
df1.shape

(2217, 28)

In [6]:
#Load the CSV into a Pandas DataFrame and display: columns names
df1.columns

Index(['match_id', 'innings', 'total_runs', 'extras', 'wickets',
       'balls_bowled', 'boundaries_4', 'boundaries_6', 'dot_balls',
       'batting_team', 'bowling_team', 'dot_ball_pct', 'extras_pct',
       'run_rate', 'powerplay_runs', 'powerplay_wickets', 'death_over_runs',
       'death_over_wickets', 'date', 'venue', 'city', 'toss_winner',
       'toss_decision', 'winner', 'player_of_match', 'method', 'season',
       'toss_win_match_win'],
      dtype='object')

In [7]:
#Load the CSV into a Pandas DataFrame and display: first 10 rows
df1.head(10)

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
0,335982,1,205,17,3,124,15,14,45,Kolkata Knight Riders,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
1,335982,2,63,19,10,101,3,3,65,Royal Challengers Bangalore,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
2,335983,1,234,6,5,124,20,16,39,Chennai Super Kings,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
3,335983,2,196,11,4,124,18,9,33,Kings XI Punjab,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
4,335984,1,122,7,8,122,14,3,60,Rajasthan Royals,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0
5,335984,2,122,10,1,97,18,1,37,Delhi Daredevils,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0
6,335985,1,154,11,7,123,18,5,53,Mumbai Indians,...,2008-04-20,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,NaN,2008.0,0.0
7,335985,2,161,5,5,123,15,6,41,Royal Challengers Bangalore,...,2008-04-20,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,NaN,2008.0,0.0
8,335986,1,100,10,10,118,6,6,72,Deccan Chargers,...,2008-04-20,Eden Gardens,Kolkata,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,NaN,2008.0,0.0
9,335986,2,84,28,5,122,5,4,75,Kolkata Knight Riders,...,2008-04-20,Eden Gardens,Kolkata,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,NaN,2008.0,0.0

In [8]:
#number of null values in each column
df1.isna().sum()

match_id                 0
innings                  0
total_runs               0
extras                   0
wickets                  0
balls_bowled             0
boundaries_4             0
boundaries_6             0
dot_balls                0
batting_team             0
bowling_team             0
dot_ball_pct             0
extras_pct               0
run_rate                 0
powerplay_runs           0
powerplay_wickets        0
death_over_runs          0
death_over_wickets       0
date                     0
venue                    0
city                   110
toss_winner              0
toss_decision            0
winner                  65
player_of_match          7
method                2175
season                   0
toss_win_match_win       0
dtype: int64

In [9]:
#data types of all columns
df1.dtypes[df1.columns]

match_id                int64
innings                 int64
total_runs              int64
extras                  int64
wickets                 int64
balls_bowled            int64
boundaries_4            int64
boundaries_6            int64
dot_balls               int64
batting_team           object
bowling_team           object
dot_ball_pct          float64
extras_pct            float64
run_rate              float64
powerplay_runs          int64
powerplay_wickets       int64
death_over_runs       float64
death_over_wickets    float64
date                   object
venue                  object
city                   object
toss_winner            object
toss_decision          object
winner                 object
player_of_match        object
method                 object
season                float64
toss_win_match_win    float64
dtype: object

In [10]:
#Filter all matches where:
#team1 = "Mumbai Indians"
#season = 2015

df1[(df1['batting_team']=='Mumbai Indians') & (df1['season']==2015)]

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
925,829705,1,165,3,3,122,18,7,50,Mumbai Indians,...,2015-04-08,Eden Gardens,Kolkata,Kolkata Knight Riders,field,Kolkata Knight Riders,M Morkel,NaN,2015.0,1.0
938,829717,2,151,8,7,125,14,9,65,Mumbai Indians,...,2015-04-12,Wankhede Stadium,Mumbai,Mumbai Indians,field,Kings XI Punjab,GJ Bailey,NaN,2015.0,0.0
941,829721,1,159,5,6,121,17,8,62,Mumbai Indians,...,2015-04-14,"Sardar Patel Stadium, Motera",Ahmedabad,Mumbai Indians,bat,Rajasthan Royals,SPD Smith,NaN,2015.0,0.0
947,829729,1,176,7,7,124,14,10,52,Mumbai Indians,...,2015-04-17,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Chennai Super Kings,A Nehra,NaN,2015.0,0.0
955,829737,1,192,17,7,128,23,10,59,Mumbai Indians,...,2015-04-19,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Mumbai Indians,Harbhajan Singh,NaN,2015.0,0.0
968,829747,2,142,11,9,128,13,6,64,Mumbai Indians,...,2015-04-23,Feroz Shah Kotla,Delhi,Mumbai Indians,field,Delhi Daredevils,SS Iyer,NaN,2015.0,0.0
971,829751,1,147,10,8,129,16,3,52,Mumbai Indians,...,2015-04-25,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Mumbai Indians,SL Malinga,NaN,2015.0,1.0
986,829769,1,178,9,5,125,18,6,41,Mumbai Indians,...,2015-05-01,Wankhede Stadium,Mumbai,Rajasthan Royals,field,Mumbai Indians,AT Rayudu,NaN,2015.0,0.0
992,829775,1,167,5,3,122,17,4,44,Mumbai Indians,...,2015-05-03,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Mumbai Indians,bat,Mumbai Indians,LMP Simmons,NaN,2015.0,1.0
1001,829783,2,144,9,5,123,9,7,48,Mumbai Indians,...,2015-05-05,Wankhede Stadium,Mumbai,Delhi Daredevils,bat,Mumbai Indians,Harbhajan Singh,NaN,2015.0,0.0
1009,829789,2,157,2,4,117,10,8,41,Mumbai Indians,...,2015-05-08,"MA Chidambaram Stadium, Chepauk",Chennai,Chennai Super Kings,bat,Mumbai Indians,HH Pandya,NaN,2015.0,0.0
1015,829795,2,192,4,7,123,15,11,40,Mumbai Indians,...,2015-05-10,Wankhede Stadium,Mumbai,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,AB de Villiers,NaN,2015.0,1.0
1024,829805,1,161,10,4,129,18,4,50,Mumbai Indians,...,2015-05-14,Wankhede Stadium,Mumbai,Kolkata Knight Riders,field,Mumbai Indians,HH Pandya,NaN,2015.0,0.0
1035,829815,2,106,8,1,88,13,3,39,Mumbai Indians,...,2015-05-17,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,bat,Mumbai Indians,MJ McClenaghan,NaN,2015.0,0.0
1036,829817,1,178,9,6,129,11,12,51,Mumbai Indians,...,2015-05-19,Wankhede Stadium,Mumbai,Mumbai Indians,bat,Mumbai Indians,KA Pollard,NaN,2015.0,1.0
1042,829823,1,196,6,5,121,16,12,43,Mumbai Indians,...,2015-05-24,Eden Gardens,Kolkata,Chennai Super Kings,field,Mumbai Indians,RG Sharma,NaN,2015.0,0.0

In [11]:
#Find all unique teams in the dataset.
#List all unique teams that have participated in IPL
teams =pd.concat([df1['batting_team'], df1['bowling_team']]).unique()
teams

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [12]:
#Find number of matches played at each venue.

counts = df1['venue'].value_counts()
counts

venue
Eden Gardens                                                             154
Wankhede Stadium                                                         148
M Chinnaswamy Stadium                                                    131
Feroz Shah Kotla                                                         119
Rajiv Gandhi International Stadium, Uppal                                100
Dubai International Cricket Stadium                                      100
MA Chidambaram Stadium, Chepauk                                           98
Sawai Mansingh Stadium                                                    94
Wankhede Stadium, Mumbai                                                  90
Punjab Cricket Association Stadium, Mohali                                70
Sheikh Zayed Stadium                                                      62
MA Chidambaram Stadium, Chepauk, Chennai                                  58
Sharjah Cricket Stadium                                                   56
Narendra Modi Stadium, Ahmedabad                                          48
Maharashtra Cricket Association Stadium                                   44
Dr DY Patil Sports Academy, Mumbai                                        40
Dr DY Patil Sports Academy                                                34
Brabourne Stadium, Mumbai                                                 34
Subrata Roy Sahara Stadium                                                32
Eden Gardens, Kolkata                                                     32
Arun Jaitley Stadium, Delhi                                               32
Kingsmead                                                                 30
M.Chinnaswamy Stadium                                                     30
Arun Jaitley Stadium                                                      30
Rajiv Gandhi International Stadium                                        30
M Chinnaswamy Stadium, Bengaluru                                          28
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow     27
Rajiv Gandhi International Stadium, Uppal, Hyderabad                      26
Sardar Patel Stadium, Motera                                              26
Maharashtra Cricket Association Stadium, Pune                             26
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                       26
SuperSport Park                                                           24
Saurashtra Cricket Association Stadium                                    22
Punjab Cricket Association IS Bindra Stadium, Mohali                      22
Punjab Cricket Association IS Bindra Stadium                              20
Sawai Mansingh Stadium, Jaipur                                            20
Brabourne Stadium                                                         20
Himachal Pradesh Cricket Association Stadium                              18
MA Chidambaram Stadium                                                    18
Holkar Cricket Stadium                                                    18
Newlands                                                                  16
New Wanderers Stadium                                                     16
Zayed Cricket Stadium, Abu Dhabi                                          16
JSCA International Stadium Complex                                        14
Barabati Stadium                                                          14
St George's Park                                                          14
Shaheed Veer Narayan Singh International Stadium                          12
Nehru Stadium                                                             10
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        10
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          10
Green Park                                                                 8
Himachal Pradesh Cricket Association Stadium, Dharamsala                   8
De Beers Diamond Oval                                                      6
Buffalo Park                                                               6
Barsapara Cricket Stadium, Guwahati                                        6
Vidarbha Cricket Association Stadium, Jamtha                               6
OUTsurance Oval                                                            4
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam         4
Name: count, dtype: int64

In [13]:
#total number of matches played in each season
df1[['match_id','season']].drop_duplicates()['season'].value_counts()

season
2013.0    76
2022.0    74
2012.0    74
2023.0    74
2011.0    73
2024.0    71
2019.0    60
2016.0    60
2010.0    60
2021.0    60
2020.0    60
2014.0    60
2018.0    60
2017.0    59
2015.0    59
2008.0    58
2009.0    57
Name: count, dtype: int64

In [14]:
df1

,match_id,innings,total_runs,extras,wickets,balls_bowled,boundaries_4,boundaries_6,dot_balls,batting_team,...,date,venue,city,toss_winner,toss_decision,winner,player_of_match,method,season,toss_win_match_win
0,335982,1,205,17,3,124,15,14,45,Kolkata Knight Riders,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
1,335982,2,63,19,10,101,3,3,65,Royal Challengers Bangalore,...,2008-04-18,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,NaN,2008.0,0.0
2,335983,1,234,6,5,124,20,16,39,Chennai Super Kings,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
3,335983,2,196,11,4,124,18,9,33,Kings XI Punjab,...,2008-04-19,"Punjab Cricket Association Stadium, Mohali",Chandigarh,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,NaN,2008.0,1.0
4,335984,1,122,7,8,122,14,3,60,Rajasthan Royals,...,2008-04-19,Feroz Shah Kotla,Delhi,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,NaN,2008.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2212,1426310,2,168,6,6,119,20,5,40,Rajasthan Royals,...,2024-05-22,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,R Ashwin,NaN,2024.0,1.0
2213,1426311,1,167,8,9,127,11,9,48,Sunrisers Hyderabad,...,2024-05-24,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Rajasthan Royals,field,Sunrisers Hyderabad,Shahbaz Ahmed,NaN,2024.0,0.0
2214,1426311,2,134,5,7,124,13,5,59,Rajasthan Royals,...,2024-05-24,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Rajasthan Royals,field,Sunrisers Hyderabad,Shahbaz Ahmed,NaN,2024.0,0.0
2215,1426312,1,100,13,10,117,8,3,62,Sunrisers Hyderabad,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,bat,Kolkata Knight Riders,MA Starc,NaN,2024.0,0.0
2216,1426312,2,103,11,2,67,10,6,28,Kolkata Knight Riders,...,2024-05-26,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,Sunrisers Hyderabad,bat,Kolkata Knight Riders,MA Starc,NaN,2024.0,0.0

In [22]:
#how many matches each team has won
# won = df1['winner'].value_counts()
# won

df1[['match_id','winner']].drop_duplicates()['winner'].value_counts()

winner
Mumbai Indians                 142
Chennai Super Kings            138
Kolkata Knight Riders          130
Royal Challengers Bangalore    114
Rajasthan Royals               110
Sunrisers Hyderabad             87
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  45
Deccan Chargers                 29
Gujarat Titans                  28
Punjab Kings                    24
Lucknow Super Giants            24
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Royal Challengers Bengaluru      7
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [16]:
#top 5 venues where most matches were played
df1['venue'].value_counts().head(5)

venue
Eden Gardens                                 154
Wankhede Stadium                             148
M Chinnaswamy Stadium                        131
Feroz Shah Kotla                             119
Rajiv Gandhi International Stadium, Uppal    100
Name: count, dtype: int64

In [17]:
#total runs scored by each team across all seasons
df1.groupby('batting_team')['total_runs'].sum()

batting_team
Chennai Super Kings            36739
Deccan Chargers                10885
Delhi Capitals                 14229
Delhi Daredevils               23022
Gujarat Lions                   4629
Gujarat Titans                  7357
Kings XI Punjab                28541
Kochi Tuskers Kerala            1758
Kolkata Knight Riders          37149
Lucknow Super Giants            7081
Mumbai Indians                 39946
Pune Warriors                   6040
Punjab Kings                    9042
Rajasthan Royals               33074
Rising Pune Supergiant          2370
Rising Pune Supergiants         1962
Royal Challengers Bangalore    35810
Royal Challengers Bengaluru     2789
Sunrisers Hyderabad            27641
Name: total_runs, dtype: int64

In [23]:
#average runs scored per innings by each team
df1.groupby('batting_team')['total_runs'].mean()

batting_team
Chennai Super Kings            154.365546
Deccan Chargers                145.133333
Delhi Capitals                 151.372340
Delhi Daredevils               142.111111
Gujarat Lions                  149.322581
Gujarat Titans                 163.488889
Kings XI Punjab                146.364103
Kochi Tuskers Kerala           125.571429
Kolkata Knight Riders          145.682353
Lucknow Super Giants           160.931818
Mumbai Indians                 150.172932
Pune Warriors                  134.222222
Punjab Kings                   161.464286
Rajasthan Royals               148.313901
Rising Pune Supergiant         148.125000
Rising Pune Supergiants        140.142857
Royal Challengers Bangalore    147.366255
Royal Challengers Bengaluru    185.933333
Sunrisers Hyderabad            148.607527
Name: total_runs, dtype: float64

In [19]:
#win percentage of each team
matches_played = df1[['match_id', 'batting_team']].drop_duplicates()
matches_played_count = matches_played['batting_team'].value_counts()
matches_won = df1[['match_id', 'winner']].drop_duplicates()
matches_won_count = matches_won['winner'].value_counts()
win_percentage = (matches_won_count / matches_played_count) * 100
win_percentage

Chennai Super Kings            58.227848
Deccan Chargers                38.666667
Delhi Capitals                 49.450549
Delhi Daredevils               41.614907
Gujarat Lions                  43.333333
Gujarat Titans                 62.222222
Kings XI Punjab                44.736842
Kochi Tuskers Kerala           42.857143
Kolkata Knight Riders          51.792829
Lucknow Super Giants           54.545455
Mumbai Indians                 54.406130
Pune Warriors                  26.666667
Punjab Kings                   42.857143
Rajasthan Royals               50.000000
Rising Pune Supergiant         62.500000
Rising Pune Supergiants        35.714286
Royal Challengers Bangalore    47.500000
Royal Challengers Bengaluru    46.666667
Sunrisers Hyderabad            47.802198
Name: count, dtype: float64

In [ ]:
#Analyze toss impact:
#how many times toss winner also won the match
temp = df1[['match_id','toss_winner','winner']].drop_duplicates()
temp['toss_win_match_win'] = temp['toss_winner'] == temp['winner']

temp['toss_win_match_win'].value_counts(normalize=True) * 100

toss_win_match_win
True     50.045662
False    49.954338
Name: proportion, dtype: float64

In [21]:
#top 5 players with most “player_of_match” awards
df1['player_of_match'].value_counts().head(5)

player_of_match
AB de Villiers    52
CH Gayle          44
RG Sharma         38
V Kohli           38
DA Warner         36
Name: count, dtype: int64